---
title: "Information for speakers"
description: |
  Notes for presenters in the matcha metaresearch webinar series.
date: "updated `r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Thank you for accepting an invitation to speak in the matcha metaresearch webinar series. 

## What we need from you

- bio
- title
- abstract
- photo 

### optional: tweetable abstract

Twitter has a character limit of 280 characters. It's useful to have a short one-sentence description of your talk.

For example: Neal Haddaway provided us with:

> #OpenSynthesis – how and why we should embrace and develop Open Science principles in evidence synthesis to maximise efficiency, rigour, transparency, legacy and impact of #SystematicReviews

which has 190 characters, allowing us to @ the speaker, as well. 

## Intended audience

Think lab meeting. 

This is a webinar series of interest to the Interdisciplinary Metaresearch Group and the Norwegian Institute for Nature Research. There will be certainly be ecologists, research software engineers, and philosophers of science in attendence.

In addition, the talks will be advertised to the general academic community, so people may join from any number disciplines with an interest in metaresearch. 

We suggest tailoring the content for a general academic audience, rather than assuming in-depth discipline-specific knowledge. Instead we invite you to frame your content from the perspective that metascience is a comparative discipline, seeking to explore what we might learn from shared scientific methodologies and practices across disciplines. 

### It might be just Matt and Charles

We're both introverts and don't truck much with the whole social media branding and whatnot. Our motivation for creating this repository of talks was to share with those who might be interested, do a little bit towards due diligence towards the spirit of open science. 

## Recorded webinars

Webinars will be recorded in Teams and uploaded to the NINA youtube channel. In addition, talk and abstract will be posted to this blog. 

## Slides

We will post the slides to this blog.

## Structure of webinar

- Short introduction from organisers describing structure of webinar
- 20-40 minute presentation from invited speaker
- Organisers invite questions via chat
- 10-20 minutes of question time, depending on length of talk
- Less than one hour total

## Opt out

If any of these elements concern you, please contact the organisers to opt out. For example, you may not wish to be recorded, or share your slides, for in progress research. 
