---
title: "Schedule"
description: |
  Speakers in the matcha metaresearch webinar series.
date: "updated: `r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The link to the matcha metaresearch seminar will be shared by the matcha slack channel. 

Join the [matcha metaresearch slack](https://docs.google.com/forms/d/e/1FAIpQLSeFPkf2Xc3RJP11YNssxxO-yLH4jEb9ATIhSnAt2WpjiuGBQw/viewform?usp=pp_url) forum.



```{r}
library(googlesheets4)
library(tidyverse)
library(kableExtra)

gs4_deauth()

speakers <- read_sheet(Sys.getenv("MATCHA_GS"), sheet = 3)


```

```{r}
speakers %>% 
  select(status, date, month, name, title, video) %>% 
  mutate(status = if_else(status == "accepted", "upcoming", status),
         title = if_else(!is.na(video), paste0("[", title, "](", video, ")"), title)
         ) %>% 
  select(-video) %>% 
  kable(format = "html") %>% 
  kable_styling("striped") %>% 
  row_spec(which(speakers$status=="presented"), bold = T, color = "white", background = "lightgrey")


```



